apiVersion: apps/v1
kind: Deployment
metadata:
  name: osg-submit
  namespace: osg-services
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: osg-submit
  template:
    metadata:
      labels:
        k8s-app: osg-submit
    spec:
      containers:
      - env:
        - name: CONDOR_HOST
          value: "flock.opensciencegrid.org" 
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        name: osg-submit
        image: htcondor/submit:el7
        ports:
        - containerPort: 31618 
        volumeMounts:
        - mountPath: /etc/condor/condor_config.local
          subPath: condor_config.local
          name: condor-config
        - mountPath: /root/secrets/token
          subPath: token
          name: flock-token
        resources:
          limits:
            cpu: 4
            memory: 3Gi
          requests:
            cpu: 3
            memory: 1Gi
      restartPolicy: Always
      volumes:
        - name: flock-token
          secret:
            secretName: osgflock-submit-token
            items:
            - key: token
              path: token
        - name: condor-config
          configMap:
             name: condor-flock-config
             items:
             - key: condor.config
               path: condor_config.local

