apiVersion: v1
kind: Service
metadata:
  name: osg-submit-service
  namespace: osg-services
spec:
  selector:
    k8s-app: osg-submit
  type: NodePort
  ports:
  - name: condor
    port: 31618
    nodePort: 31618
    protocol: TCP
    targetPort: 31618
