apiVersion: v1
kind: Service
metadata:
  name: osg-submit-service
  namespace: osg-services
spec:
  selector:
    k8s-app: osg-submit
  type: ClusterIP
  ports:
  - name: condor
    port: 39618
    targetPort: 39618
    protocol: TCP
