apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osgvo-submit-storage
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
